---
- name: Configure
  hosts: apache
  become: yes
  gather_facts: False
  tasks:
    - name: Disable default site
      command: a2dissite 000-default.conf
      failed_when: false
 
    - name: Remove default site config
      file:
        state: absent
        path: /etc/apache2/sites-available/000-default.conf

    - name: Create new site directory
      file:
        state: directory
        path: /var/www/{{ properties.site_name }}
    
    - name: Copy site html
      template:
        src: site/index.html
        dest: /var/www/{{ properties.site_name }}/index.html
        mode: '0755'
    
    - name: Add site config
      template:
        src: conf/hw-site.conf
        dest: /etc/apache2/sites-available/hw-site.conf
        mode: '0755'
    
    - name: Enable new site
      command: a2ensite hw-site.conf


