- name: Start
  hosts: apache
  become: yes
  gather_facts: False
  tasks:
  - name: get service facts
    service_facts:

  - name: Prevent apache2 auto-starting on install
    shell: ln -s /dev/null /etc/systemd/system/apache2.service
    when: ansible_facts.services["apache2"] is not defined

  - name: Install apache2
    apt:
      update_cache: yes
      name: apache2
    register: apache_install
    until: '(apache_install["stderr"]|length == 0) or ("Could not get lock" not in apache_install["stderr"])'
    retries: 60
    delay: 1
    when: ansible_facts.services["apache2"] is not defined

  - name: Restart apache2
    systemd:
      masked: no
      state: restarted
      name: apache2