---
- name: Stop
  hosts: apache
  become: yes
  gather_facts: False
  tasks:
    - name: get service facts
      service_facts:
 
    - name: Stop apache2
      systemd:
        state: stopped
        name: apache2
      when: ansible_facts.services["apache2"] is defined
